-- register table column attribute's some changed. (정현재)
ALTER TABLE REGISTER MODIFY JOBINFO VARCHAR2(350);
ALTER TABLE REGISTER MODIFY CONTENT VARCHAR2(200) NULL;

--강사가 강의실 번호를 참조 받음
alter table teacher add (roomno number(5));
ALTER TABLE teacher
ADD FOREIGN KEY (roomno) REFERENCES sturoom(roomno);

-- stuCur 테이블 curriculum으로 이름 변경
rename studyCur to curriculum;

-- 커리큘럼 테이블 null값 허용
alter table curriculum modify(curNo null, tchNo null);

-- 학생 테이블 행정부 번호 컬럼 삭제
alter table student drop column admNo;

-- register 테이블 submitValue -> file1로 변경
alter table register rename column submitValue to file1;

-- register 테이블 file2컬럼 추가
alter table register add(file2 VARCHAR2(10));

-- register ���̺� file1, file2, gubun �÷� ������ ����
alter table register modify(file1 VARCHAR2(50));
alter table register modify(file2 VARCHAR2(50));
alter table register modify(gubun VARCHAR2(100));

------member 테이블 변경
ALTER TABLE MEMBER MODIFY (MEMPW VARCHAR2(30) NOT NULL,
							MEMID VARCHAR2(30) NOT NULL,
							MEMNAME VARCHAR2(30) NOT NULL,
							MEMADDRESS VARCHAR2(100) NOT NULL,
							MEMPHONE VARCHAR2(20) NOT NULL);
------멤버 테이블 속성 널값으로 변경							
ALTER TABLE MEMBER ADD MEMTEL VARCHAR2(20) NULL;
ALTER TABLE MEMBER ADD MEMGENDER VARCHAR2(20) NOT NULL;
ALTER TABLE MEMBER ADD EMAILAGREE VARCHAR2(5) NOT NULL;
ALTER TABLE MEMBER ADD JOINDAY VARCHAR2(20) NOT NULL;


-- ATTEND table column attribute's 아주 많이 changed. (한국인)
ALTER TABLE ATTEND DROP COLUMN attdValue;
ALTER TABLE ATTEND ADD attdValue1 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue2 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue3 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue4 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue5 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue6 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue7 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue8 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue9 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue10 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue11 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue12 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue13 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue14 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue15 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue16 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue17 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue18 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue19 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue20 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue21 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue22 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue23 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue24 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue25 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue26 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue27 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue28 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue29 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue30 VARCHAR2(10) NULL;
ALTER TABLE ATTEND ADD attdValue31 VARCHAR2(10) NULL;

--삭제ALTER TABLE member DROP COLUMN joinDate;

--삭제ALTER TABLE teacher ADD tchName VARCHAR2(30) NULL;

ALTER TABLE ATTEND DROP COLUMN attdValue1;
ALTER TABLE ATTEND DROP COLUMN attdValue2;
ALTER TABLE ATTEND DROP COLUMN attdValue3;
ALTER TABLE ATTEND DROP COLUMN attdValue4;
ALTER TABLE ATTEND DROP COLUMN attdValue5;
ALTER TABLE ATTEND DROP COLUMN attdValue6;
ALTER TABLE ATTEND DROP COLUMN attdValue7;
ALTER TABLE ATTEND DROP COLUMN attdValue8;
ALTER TABLE ATTEND DROP COLUMN attdValue9;
ALTER TABLE ATTEND DROP COLUMN attdValue10;
ALTER TABLE ATTEND DROP COLUMN attdValue11;
ALTER TABLE ATTEND DROP COLUMN attdValue12;
ALTER TABLE ATTEND DROP COLUMN attdValue13;
ALTER TABLE ATTEND DROP COLUMN attdValue14;
ALTER TABLE ATTEND DROP COLUMN attdValue15;
ALTER TABLE ATTEND DROP COLUMN attdValue16;
ALTER TABLE ATTEND DROP COLUMN attdValue17;
ALTER TABLE ATTEND DROP COLUMN attdValue18;
ALTER TABLE ATTEND DROP COLUMN attdValue19;
ALTER TABLE ATTEND DROP COLUMN attdValue20;
ALTER TABLE ATTEND DROP COLUMN attdValue21;
ALTER TABLE ATTEND DROP COLUMN attdValue22;
ALTER TABLE ATTEND DROP COLUMN attdValue23;
ALTER TABLE ATTEND DROP COLUMN attdValue24;
ALTER TABLE ATTEND DROP COLUMN attdValue25;
ALTER TABLE ATTEND DROP COLUMN attdValue26;
ALTER TABLE ATTEND DROP COLUMN attdValue27;
ALTER TABLE ATTEND DROP COLUMN attdValue28;
ALTER TABLE ATTEND DROP COLUMN attdValue29;
ALTER TABLE ATTEND DROP COLUMN attdValue30;
ALTER TABLE ATTEND DROP COLUMN attdValue31;
ALTER TABLE ATTEND DROP COLUMN attdDate;

--한국인삭제ALTER TABLE ATTEND ADD attdDate date NULL;

--한국인삭제ALTER TABLE ATTEND ADD atvNo number(4) NULL;

--한국인삭제ALTER TABLE ATTEND DROP COLUMN atvno;
-- notice 테이블 컬럼 변경
alter table notice add(test clob);
alter table notice drop column content;
alter table notice rename column test to content;
alter table notice modify (name varchar2(50));
alter table notice modify (title varchar2(100));

--한국인 테이블 참조 변경 attend에서 stuNo를 참조 받는게 아닌 student에서 attdNo를 참조하도록
alter table attend drop column stuNo;
ALTER TABLE student ADD attdNo number(5) NULL;
ALTER TABLE student
	ADD ( FOREIGN KEY (attdNo) REFERENCES attend(attdNo) ON DELETE SET NULL);
	
select * from student;

select * from attend;

update student set attdNo = 1 where stuNo = 11;

